# This runs code signing for .nupkg files built on MacOS or Linux
parameters:
  inputName: ''

jobs:
- template: default-build.yml
  parameters:
    codeSign: true
    dependsOn:
    - ${{ parameters.inputName }}_build
    condition: in(variables['_SignType'], 'test', 'real')
    jobName: CodeSign_Xplat_${{ parameters.inputName }}
    jobDisplayName: "Code-sign ${{ parameters.inputName }} packages"
    agentOs: Windows
    installNodeJs: false
    installJdk: false
    buildSteps:
    - task: DownloadBuildArtifacts@0
      displayName: Download ${{ parameters.inputName }} artifacts
      inputs:
        artifactName: ${{ parameters.inputName }}_Packages
        downloadPath: $(Build.StagingDirectory)/deps/
        itemPattern: '**/*.nupkg'
    - task: MSBuild@1
      displayName: Code-sign .nupkg files
      inputs:
        solution: eng\tools\XplatPackageSigner\XplatPackageSigner.proj
        msbuildArguments: /p:SignType=$(_SignType) /p:DirectoryToSign=$(Build.StagingDirectory)\deps\${{ parameters.inputName }}_Packages\
    artifacts:
    - name: ${{ parameters.inputName }}_Packages_Signed
      path: $(Build.StagingDirectory)\deps\${{ parameters.inputName }}_Packages\
