jobs:
- template: default-build.yml
  parameters:
    buildScript: ./src/SiteExtensions/LoggingAggregate/build.cmd
    buildArgs: "-ci"
    jobName: SiteExtensions
    jobDisplayName: "Build logging site extension"
    artifacts:
      publish: true
      path: 'src/SiteExtensions/LoggingAggregate/artifacts/'
